stages:
  - build
  - deploy

build-apk:
  stage: build
  image: openjdk:17
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/release/app-release.apk
    expire_in: 1 week

deploy-firebase:
  stage: deploy
  image: node:latest
  dependencies:
    - build-apk
  script:
    - npm install -g firebase-tools
    - firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk --app "$FIREBASE_APP_ID" --token "$FIREBASE_TOKEN" --groups "testers"
  only:
    - main