package com.livewire.Repository;

import android.content.Context;

import androidx.room.Room;

import com.livewire.Database.Powerplant;
import com.livewire.Entity.DynamoResponse;

// Diagnostic data models used by the repository
import com.livewire.Model.AIModel;
import com.livewire.Model.DiagnosticEvent;
import com.livewire.Model.DiagnosticReport;

// Service responsible for communication with the backend/AI server
import com.livewire.Service.AIService;

// Chat message model used when submitting prompts
import com.livewire.Model.ChatMessage;

// Logger that stores diagnostic events generated by the application
import com.livewire.Service.DiagnosticEventLogger;

// Java List collection
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.List;

/**
 * Repository responsible for coordinating application data operations

 * The repository sits between the UI/ViewModel layer and the AIService

 * Instead of the Activity or ViewModel communicating directly with
 * AIService, it can communicate with this repository

 * Main responsibilities:

 * 1. Submit chat messages to the AI service
 * 2. Retrieve diagnostic information
 * 3. Attach locally stored diagnostic events to diagnostic reports
 * 4. Send diagnostic reports to the AI for analysis
 * 5. Pass results/errors back to the caller through callbacks
 */

public class MainRepository {

    private final Powerplant powerplant;


    // Service used to communicate with the backend AI API
    // The repository owns this service instance and delegates
    // network-related operations to it
    private final AIService aiservice = new AIService();

    private final ExecutorService databaseExecutor =
            Executors.newSingleThreadExecutor();

    public void saveDynamo(
            DynamoResponse response,
            DynamoRepositoryCallback callback) {

        databaseExecutor.execute(() -> {

            try {

                powerplant
                        .dynamoResponseDao()
                        .insert(response);

                if (callback != null) {
                    callback.onComplete();
                }

            } catch (Exception e) {

                if (callback != null) {
                    callback.onError(e.getMessage());
                }
            }
        });
    }

    public void getDynamos(
            DynamosRepositoryCallback callback) {

        databaseExecutor.execute(() -> {

            try {

                List<DynamoResponse> responses =
                        powerplant
                                .dynamoResponseDao()
                                .getAll();

                callback.onResult(responses);

            } catch (Exception e) {

                callback.onError(e.getMessage());
            }
        });
    }

    public void deleteDynamo(
            DynamoResponse response,
            DynamoRepositoryCallback callback) {

        databaseExecutor.execute(() -> {

            try {

                powerplant
                        .dynamoResponseDao()
                        .delete(response);

                if (callback != null) {
                    callback.onComplete();
                }

            } catch (Exception e) {

                if (callback != null) {
                    callback.onError(e.getMessage());
                }
            }
        });
    }

    public void deleteAllDynamos(
            DynamoRepositoryCallback callback) {

        databaseExecutor.execute(() -> {

            try {

                powerplant
                        .dynamoResponseDao()
                        .deleteAll();

                if (callback != null) {
                    callback.onComplete();
                }

            } catch (Exception e) {

                if (callback != null) {
                    callback.onError(e.getMessage());
                }
            }
        });
    }

    public interface DynamoRepositoryCallback{
        void onComplete();
        void onError(String error);
    }

    public interface DynamosRepositoryCallback{
        void onResult(List<DynamoResponse> responses);
        void onError(String error);
    }
    public MainRepository(Context context) {

        powerplant = Room.databaseBuilder(
                context.getApplicationContext(),
                Powerplant.class,
                "livewire_powerplant"
        ).build();
    }

    // Chat
    /**
     * Callback used when submitting a normal chat prompt

     * onResult() is called when the AI successfully responds
     * onError() is called when the request fails
     */
    public interface RepositoryCallback {
        void onResult(String result);
        void onError(String error);
    }

    /**
     * Sends a conversation to the AI service

     * The repository does not perform the actual network request
     * Instead, it delegates the request to AIService

     * @param messages Chat conversation/history to send to the AI
     * @param callback Callback that receives the response or error
     */
    public void submitPrompt(
            List<ChatMessage> messages,
            AIModel model,
            RepositoryCallback callback) {

        // Delegate the request to the AI service
        aiservice.sendPrompt(
                messages,
                model.getId(),
                new AIService.ServiceCallback() {

            /**
             * Called by AIService when the AI responds successfully
             */
            @Override
            public void onResult(String response) {

                // Forward the result to whoever called the repository
                callback.onResult(response);
            }

            /**
             * Called by AIService when something goes wrong
             */
            @Override
            public void onError(String error) {

                // Forward the error to the caller
                callback.onError(error);
            }
        });
    }

    // Diagnostics
    /**
     * Callback specifically for diagnostic reports

     * A separate callback type is used because the successful result
     * is a DiagnosticReport rather than a String
     */
    public interface DiagnosticsRepositoryCallback {
        void onResult(DiagnosticReport report);
        void onError(String error);
    }

    /**
     * Callback used when AI analysis of diagnostics completes

     * The AI analysis is returned as a string
     */
    public interface AnalysisRepositoryCallback {
        void onResult(String analysis);
        void onError(String error);
    }

    /**
     * Retrieves the current diagnostic information

     * The process is:
     * 1. Ask AIService for the server diagnostics
     * 2. Retrieve locally recorded diagnostic events
     * 3. Add those events to the DiagnosticReport
     * 4. Return the completed report to the caller

     * @param callback Callback receiving the completed diagnostic report
     */
    public void getDiagnostics(DiagnosticsRepositoryCallback callback) {

        // Ask AIService to retrieve diagnostics from the backend
        aiservice.getDiagnostics(
                new AIService.DiagnosticsCallback() {

                    /**
                     * Called when the backend returns diagnostic information
                     */
                    @Override
                    public void onResult(DiagnosticReport report) {

                        // Retrieve diagnostic events recorded locally
                        // by the Android application
                        List<DiagnosticEvent> events =
                                DiagnosticEventLogger.getEvents();

                        // Add the locally collected events to the
                        // diagnostic report returned by the server
                        // This combines server-side diagnostics with
                        // client-side application history
                        report.setEvents(events);

                        // Return the completed report to the caller
                        callback.onResult(report);
                    }

                    /**
                     * Called when retrieving diagnostics fails
                     */
                    @Override
                    public void onError(String error) {

                        // Forward the error to the repository caller
                        callback.onError(error);
                    }
                }
        );
    }

    /**
     * Sends a diagnostic report to the AI for analysis

     * AIService performs the actual network communication
     * This repository method simply coordinates the request and
     * forwards the result back to the caller

     * @param report Diagnostic information to analyze
     * @param callback Callback receiving the AI analysis
     */
    public void analyzeDiagnostics(DiagnosticReport report, AnalysisRepositoryCallback callback) {

        // Send the diagnostic report to the AI service
        aiservice.analyzeDiagnostics(
                report,
                new AIService.AnalysisCallback() {

                    /**
                     * Called when the successfully analyzes the report
                     */
                    @Override
                    public void onResult(String analysis) {

                        // Forward the AI-generated analysis
                        callback.onResult(analysis);
                    }

                    /**
                     * Called when the analysis request fails
                     */
                    @Override
                    public void onError(String error) {

                        // Forward the error to the caller
                        callback.onError(error);
                    }
                }
        );
    }
}
